services:
  backend:
    build: ./backend
    container_name: quizzapp-backend
    expose:
      - "8080"

  frontend:
    build: ./frontend
    container_name: quizzapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend